ogaogs/receipt-scanner

prisma/migrations/20240927114326_2024_9_27/migration.sql
prisma/migrations/20240927130002_initial_schema/migration.sql
prisma/seed.ts

予算のseedingを行った。
8月と9月分の予算を作成した。
各カテゴリーごとに作成した。
Closes # 40
prismaがUTCタイムでの保存しかできずに、`new Date(2024, 8)`(jsのdatetimeは月が0から始まるため、8は9月を意味する。)とすると、`2024-08-31-15:00`のようになる。
今回、yearとmonthのみを考えればいいので、ダミーデータには、9月の予算のyear_monthを`new Date(2024, 8, 15)`としている。

🗃️ 予算のseedingを行った (#40)

---

src/_components/layouts/Sidebar/Sidebar.tsx
src/lib/db/expense.ts
src/lib/db/index.ts
src/types/expense.ts
src/types/index.ts

現在ある出費月の範囲を["YYY-MM or M"]で取得するようにした。
- Prismaのaggregateを使って、_miniと_maxで出費の最初の月と最後の月を取得した
- [✨1番初めの出費と最後の出費を取得できるようにした (#56 #54)](https://github.com/AyumuOgasawara/receipt-scanner/commit/2f3981575211a59140dac7c40727a8a06694f100)
- [♻️ FirstAndLastExpenseDateの方をglobalで使用したいために、exportできるようにし、わかりやすいように変数名を変更した(#56 #54)](https://github.com/AyumuOgasawara/receipt-scanner/commit/16d129a83335434d2c1edc8e606b779c030d4282)
- 取得した最初の月から１ヶ月づつ繰り上げて最後の月までwhileを回し、出費月範囲を"YYYY-MM or M"の形で取得した。
- [✨Siderbarで出費月の範囲の全ての月を取得し"YYYY-MM or M"の形でリストに入れた (#54 #56)](https://github.com/AyumuOgasawara/receipt-scanner/commit/69e216009984e298256a556f877623960f74612b)
出費の最初の日にち：`2024-07-31T14:05:20.658Z` -> 2024年7月 (日本時間)
出費の最後の日にち：`2024-09-30T23:13:28.683Z` -> 2024年10月 (日本時間)
``` ts
const monthsInRange = …
```

現在ある出費月の範囲をstring[]で取得した (#56)

---

src/app/layout.tsx

childrenとsidebarを囲んでいたBoxにpaddingTopをつけることで、childrenを囲むBoxがheader分ずれていたバグを修正
Closes #51 
https://github.com/AyumuOgasawara/receipt-scanner/issues/51#issuecomment-2391219600
https://github.com/user-attachments/assets/0487b933-c4c2-4858-b6ff-acbbb4e5fac5

🐛 childrenを囲むBoxがheader分ずれていた部分を修正 (#51)

---

src/_components/features/expenses/ExpenseDialog.tsx
src/_components/features/expenses/ExpensesTable.tsx
src/_components/features/expenses/index.tsx
src/_components/features/expenses/type.ts
src/app/expenses/page.tsx

出費一覧から、特定の出費を選択するとダイアログを出して詳細を表示するようにした
-  [✨ 出費一覧から列を選択するとその列の詳細画面がダイアログで出るようにした(#66)](https://github.com/AyumuOgasawara/receipt-scanner/commit/c49441af1ff5e1d3196f20585c4cbdb2ef7354c8)
- [✨ カテゴリーをドロップダウンで選べれるようにした (#70)](https://github.com/AyumuOgasawara/receipt-scanner/commit/5e9e7297e848e7a7cda506f09466dc3d0aace757)
- [💄 出費一覧と詳細ダイアログのUIを整えた (#70)](https://github.com/AyumuOgasawara/receipt-scanner/commit/3426c1ea0647eaae54105b96fd7608debdbd9078)

✨ 出費一覧から特定の出費をダイアログで表示するようにした (#70)

---

src/_components/layouts/Sidebar/Sidebar.tsx

以下のエラーメッセージがコンソールに出ていたため、FormControlの中に一つのSelectが入るようにしエラーをなくした
FormControlの下に二つのSelectを入れていたが、FormControlには一つのSelectしか入らなかったため、修正した
Closes #71

🐛 FormControlの中に一つのSelectが入るようにした (#71)

---

package-lock.json
package.json
src/_components/features/expenses/ExpenseDialog.tsx

出費の詳細ダイアログの項目を制御した。
- 日付項目をDate Pickerを使い、日付しか選択できないようにした。
- 金額の項目を数字しか入れれないようにした
- [⚡️ 金額に円マークをつけ、数字しか入力できないようにした (#76)](https://github.com/AyumuOgasawara/receipt-scanner/commit/8cefb159fa7c791c98c779a12f395a44932554f3)
- `InputAdornment`を使用して、円マークを先頭につけた
- `type="number"`をつけることで、数字しか入力できなくした
- [⚡️ 日付の選択でDate Pickerを使用するようにし日本語表記にした (#76)](https://github.com/AyumuOgasawara/receipt-scanner/commit/059583f72f97a747cb541b28372680342039cf6c)
- `x-date-pickers`と`dayjs`を使った
- `calendarHeader: {format: "YYYY年MM月", // カレンダーの年月の部分}`、`format="YYYY年MM月DD" `で日本語表記にした
https://github.com/user-attachments/assets/7bc0261a-31b3-493b-a35a-0a80d544c615
金額はeを数字として扱うようになっている。

⚡️ 出費の詳細ダイアログの項目を制御した(#76)

---

src/_components/features/expenses/ExpenseDialog.tsx
src/_components/features/expenses/ExpensesTable.tsx
src/_components/features/expenses/expensesServer.ts
src/app/expenses/page.tsx
src/lib/db/expense.ts
src/lib/db/index.ts
src/utils/time.ts

出費の詳細ダイアログで変更し、更新を押下すると、更新時に入力されていたデータが一覧に反映されるようにした
- まずダイアログで更新ボタンが押された際にその内容をログで出力
- [✨ ダイアログで更新された出費を取得し、ログで出力するようにした (#74)](https://github.com/AyumuOgasawara/receipt-scanner/commit/2a73fdfa2bf019653a85e4bc472f4fae01b8a2f3)
- prismaを使って、DBの出費のUPDATEをできる関数を実装した
- [✨ expenseを更新できるようにprismaを使った関数を実装 (#74)](https://github.com/AyumuOgasawara/receipt-scanner/commit/3cafea927ceebad08a73223163f9f2a92827c69a)
- 2024年10月1日 -> Date(2024, 9, 1)になるような関数を実装
- [✨ "YYYY年MM月DD日"をDateに変換する関数を実装 (#74)](https://github.com/AyumuOgasawara/receipt-scanner/commit/ec0e661ca542d70795b6b0226a4371216aa35788)
- 更新ボタンを押下するとDBのデータが更新されるようにした
- [✨ 更新ボタンを押すと、データが更新されるように実装した (#74)](https://github.com/AyumuOgasawara/receipt-scanner/pull/79/commits/0b30ce7de1a27b1450567cb440379c62987ec29e) 
- …

出費詳細ページで更新ボタンの実装を行う。

---

src/_components/features/expenses/ExpenseDialog.tsx
src/_components/features/expenses/expensesServer.ts
src/lib/db/expense.ts
src/lib/db/index.ts

- 出費詳細ページで削除ボタンを押下し、特定の出費を削除する実装をした。
- 削除した後に出費一覧を更新した
- [✨ 特定の出費をDBから削除する関数の実装 (#75)](https://github.com/AyumuOgasawara/receipt-scanner/commit/f2f5660892096e9bc0d2edb2e875194536f35fd5)
- [✨ 削除ボタンを押下した際に特定のデータを削除し、一覧表示を更新するようにした (#75)](https://github.com/AyumuOgasawara/receipt-scanner/commit/bd0653a99e38475b68925deded033fc657272078)
https://github.com/user-attachments/assets/241c5872-2084-42dc-b0a4-872b75b74e4b
Closes #75

✨ 出費詳細ページで削除ボタンを押下し、特定の出費を削除する実装をした(#75)

---

src/_components/common/BarsDataset/BarsDataset.tsx
src/_components/features/dashboard/UpperDashboard.tsx
src/_components/features/expenses/ExpensesTable.tsx
src/utils/financial.ts

ダッシュボード下部のy軸のメモリが見切れるバグを修正を10万以上の金額は表示の仕方を(100,00 -> 10万)に変更した
Closes #50 
10万から、表示の仕方が変わっている
- 表示するメモリが金額のフォーマットになるようにした
- [✨ 金額のフォーマッターで¥マークをつけるかどうか選べるようにした (#50)](https://github.com/AyumuOgasawara/receipt-scanner/commit/458e046d3ffd1ec84eaec13901c8b85f5fb04ffe)
- 10万以上だと、10万と表示されるようにした
- [🐛 y軸が見切れるバグを表示方法を10万以上で変更することによって、修正した (#50)](https://github.com/AyumuOgasawara/receipt-scanner/commit/17253e1f0cd83608c230ac2605e9ef5a4ea0c0e9)

🐛 ダッシュボード下部のy軸のメモリが見切れるバグを修正

---

src/_components/features/dashboard/UpperDashboard.tsx
src/_components/features/expenses/ExpensesTable.tsx
src/_components/layouts/Sidebar/Sidebar.tsx
src/utils/time.ts

サイドバーにあるページ遷移のドロップダウンから"dashbord"、"expenses"、"budgets"に遷移できるようにした
- onChangeとuseRouterを使用してドロップダウンが変更された際に、変更されたバリューのページに遷移できるようにした。その際にselectedPageが更新され、ドロップダウンのvalueが変更され、見た目が制御されるようにした。
- usePathnameを使用して、現在いるページを取得し、リロードした際にドロップダウンにそのページが再び表示されるようにした
- [✨ dateFormatのmonthを"long"か"2-digit"で選べるようにした (#83)](https://github.com/AyumuOgasawara/receipt-scanner/commit/4b9148c600fad1c7052018c747d4546f7e89ac7c)
- [✨ サイドバーでページ遷移ができるようにした (#83)](https://github.com/AyumuOgasawara/receipt-scanner/commit/80c36b5c541029f1641a86f8f2d7c7f13d2d1a9c)
https://github.com/user-attachments/assets/0b145642-43e5-45c2-8060-b8f6badd6528

✨ サイドバーでページが遷移できるようにした (#83)

---

src/_components/features/sidebar/Sidebar.tsx
src/_components/features/sidebar/type.ts
src/_components/features/sidebar/yearMonthElements.ts
src/app/dashboard/page.tsx
src/app/expenses/page.tsx

サイドバーの年月を指定するドロップダウンを選択すると、dateクエリがセットされ、そのdateクエリを各ページで取得して、月毎のデータが一覧できるようにした
https://github.com/user-attachments/assets/90e80033-9b3e-46d5-a4f6-f7b164b385cf
- 年月ドロップダウンの要素やdateのクエリを親コンポーネントである、各ページから取得するようにし、年月ドロップダウンが変わると、dateクエリがセットされるようにした
- [✨ サイドバーで日付を選択すると、クエリにdateがセットされるようにしたし、リロードしするとセットされているクエリをバリューにもつ年月がドロップダウンに入るようにした(#64)](https://github.com/AyumuOgasawara/receipt-scanner/commit/3e5de2ea10de3534b1a4d5613ff37cc8a7f719ae)
- ページの切り替えドロップダウンでも、dateクエリを一緒にpushするようにした
- [✨ ページの切り替えの際にdateクエリも一緒にpushするようにした (#64)](https://github.com/AyumuOgasawara/receipt-scanner/commit/77de9e745d9e53a571ee0b8e01a4201841b7e281)
- 各ページコンポーネントから子コンポーネントに送るtargetDateをクエリのdateと一緒に動的に変化するようにした
- [✨ 各ページのtargetDateをクエリから取得したdateと同じになるようにした (#64)](https://github.com/AyumuOgasawara/receipt-scanner/commit/2a …

✨ サイドバーから月を指定できるようにした (#64)

---

package-lock.json
package.json
src/_components/features/sidebar/SidebarServer.ts
src/lib/s3.ts

"@aws-sdk/client-s3"と "@aws-sdk/s3-request-presigner"をインストールした。
そしてNextからs3に画像をアップロードできるようにした
- ライブラリのインストール
- [➕ aws-sdkのインストール (#101)](https://github.com/AyumuOgasawara/receipt-scanner/commit/a22ffd53a4f56fcf1c4a53ff566d1e2e8e285d56)
- generatePutPreSignedURLでPreSignedURLの発行。
- uploadFileToS3でアップロード
"use sercer"をつけないと、以下のエラーが表示される。
``` sh
["Error: Resolved credential object is not valid" while executing putObject command](https://stackoverflow.com/questions/75530571/aws-sdk-s3-client-throws-error-resolved-credential-object-is-not-valid-while)
```
book-offのコピー.pngを解析すると、s3にアップロードされた。
Closes #101

✨nextからs3に画像をアップロードできるようにした(#101)

---

prisma/migrations/20241020035142_initial_schema/migration.sql
prisma/schema.prisma
src/_components/features/expenses/ExpenseDialog.tsx
src/app/budgets/page.tsx
src/app/dashboard/page.tsx
src/app/expenses/page.tsx
src/lib/db/expense.ts

- [🗃️ filePath -> filrNameに変更し、ユニークではなくてはならないようにした (#103)](https://github.com/AyumuOgasawara/receipt-scanner/commit/1c4395b3bc629820ad52301e92784216b7443027)
- onDelete: Cascadeをつけて、出費削除時にレシートも削除されるようにした
- [🗃️　レシートを出費と共に削除できるようにしいた (#103)](https://github.com/AyumuOgasawara/receipt-scanner/commit/3ca0f6e2fbb0090f96ce59768bf9858c2cd9a472)
- また、同じレシートを更新すると、更新できないエラーメッセージが出るようにした。
- [💡 エラーメッセージを変更した (#103)](https://github.com/AyumuOgasawara/receipt-scanner/commit/f249bfe30475ecc4f3943fd1133f4ea52bacd57d)
レシートが入っているデータベースに対して、削除ができるようになった。
https://github.com/user-attachments/assets/d1fa6adc-a58e-4d9e-8864-85be541cf42e
現在は出費から同じレシートを入れるとエラーが出るようになっている。別イシューで対応。

🗃️ DBのレシートテーブルを更新した (#103)

---

src/_components/features/sidebar/CreateExpenseDialog.tsx
src/_components/features/sidebar/Sidebar.tsx
src/_components/features/sidebar/SidebarServer.ts
src/_components/features/sidebar/type.ts
src/lib/s3.ts

- 初めにカレンダーの初期値がundefinedだが、UI上では本日の日付が入っていたため、混乱を招かぬように、初期値を本日の日付にした
- PythonとNextの出費詳細でレシート画像が見れるようにGetPreSignedURLを発行した。
- GetObjectCommandを使用してGetPreSignedURLを発行した
- putとgetの場合のpreSignedURLの発行の仕方が似ていたため、一つにまとめた。」
- 解析を押下すると画像がアップロードされたため、デグレなし
- getPreSighnedURlを確認することができた。
Closes #106

✨ generateGetPreSignedURLを作成し、画像データをs3から取得できるpre signed urlを発行できるようにした (#106)

---

src/_components/features/expenses/ExpenseDialog.tsx
src/_components/features/expenses/ExpensesServer.ts
src/_components/features/expenses/ExpensesTable.tsx
src/_components/features/expenses/ShowReceipt.tsx
src/_components/features/expenses/index.tsx
src/_components/features/expenses/type.ts
src/_components/features/sidebar/SidebarServer.ts
src/lib/db/expense.ts
src/lib/s3.ts
src/types/index.ts
src/types/receipt.ts

出費詳細ページでs3からダウンロードしたレシート画像を表示するようにした
- 出費を取得する際にレシートも取得するようにした。そのため、prismaで取得する時や返り値の型を変更した
- [✨ 出費に紐づくレシートも取得するようにした (#106)](https://github.com/AyumuOgasawara/receipt-scanner/commit/f39cd5d6c74b07b60b23c1f707b039653d7f0ecd)
- [🏷️ 月毎の出費の型にレシートの型を追加し、キャメルケースに整えた (#106)](https://github.com/AyumuOgasawara/receipt-scanner/commit/c87489a8263358a086d100e6ba55f1f73259f8e3)
- s3からダウンロードができるようにfileNameがundefinedでないときにgetPreSignedURLを発行した
- [✨ 取得したレシートがundefinedでないときにgetPreSignedURLを発行するようにした (#106)](https://github.com/AyumuOgasawara/receipt-scanner/commit/8f85ba9d699be820d27f3da9101aa4f61fdf087e)
- レシートを表示するUIを整え、取得したgetPreSignedURLをフロントに返し、表示させた。また、ダイアログが閉じられた際に、セットされていた画像がnullになるようにした
- [✨ 取得したpreSignedURLをフロントに返し、レシートを表示した。また、ダイアログが閉じるとセットされている画像がnullになるようにした(#108 …

✨ 出費詳細ページでレシートを表示されるようにした (#108)

---

src/_components/common/Style/style.ts
src/_components/features/dashboard/LowerDashboard.tsx
src/_components/features/dashboard/UpperDashboard.tsx
src/_components/features/expenses/ExpenseDialog.tsx
src/_components/features/expenses/ExpensesServer.ts
src/_components/features/expenses/ExpensesTable.tsx
src/_components/features/sidebar/AddExpenseDetail.tsx
src/_components/features/sidebar/CreateExpenseDialog.tsx
src/_components/features/sidebar/SidebarServer.ts
src/lib/db/index.ts
src/lib/db/receipt.ts

出費の新規作成ページのレシートのアップロードと、店名と金額に、更新ページの店名と金額にのバリデーションをつけた。
- レシートはユニークのため、すでに同じファイル名がある場合にはfileNameがセットされないようにした 
- [🥅 レシートのgfileNameがすでにある際には画像がセットされないようにした (#105)](https://github.com/AyumuOgasawara/receipt-scanner/commit/cb00108327a4312c4b1667e46f9a3ec27729aa34)
- エラーメッセージの色をstyle.tsとして持ちたかったため、commonコンポーネントにstyle.tsを作成し、色はそこから取得するようにした。
- [💄 commonコンポーネントにsytleの色を追加した (#105)](https://github.com/AyumuOgasawara/receipt-scanner/commit/512610abcedc6186b0bb1fd7f2049a17e93db746)
- [🦺 新規追加ページの店名と金額にバリデーションをつけた (#105)](https://github.com/AyumuOgasawara/receipt-scanner/commit/a89d9ff0c21ad9f9533b798455b1c38bb71ce9e9)
- 出費更新ページでは、親コンポーネントで選択されたものをSlectedItemとして渡していたが、ダイアログに表示されるのは選択されている時のみだから、selectedItemのnullの可能性をなくした
- [🦺 出費の更新ページでバリデーションを店名と金額にバリデーションをつけた (#105, …

🦺 出費ページの新規作成、更新の際のバリデーションをつけた (#105, #95)

---

src/_components/features/expenses/ExpensesServer.ts
src/_components/features/sidebar/AddExpenseDetail.tsx
src/_components/features/sidebar/CreateExpenseDialog.tsx
src/_components/features/sidebar/SidebarServer.ts
src/utils/analyzeReceipt.ts
src/utils/time.ts

解析ボタンを押下後にPython側のAP Iに向けてPOSTを行う。
返ってきた値をフロントで使いやすいように変換して、フロントに返す。
結果、解析し、解析結果がフロントに反映されるようになった。
https://github.com/user-attachments/assets/e742ff6f-6e27-412e-a441-c9df796cb38a

✨ Pythonの画像解析APIを叩き、レシート解析を行うと解析結果が反映されるようにした (#111)

---

src/_components/common/Style/style.ts
src/_components/features/sidebar/Sidebar.tsx

以下を実装し、サイドバーを整えた
- サイドバーのサイズにminWidthとmaxWidthを設定した
- 中のコンポーネントのサイズのwidthを100%にした
- 名言カードを下揃えにし、後のものを上揃えにした
Closes #88

💄 サイドバーのレイアウトを整えた (#88)

---

src/_components/features/budgets/BudgetsTable.tsx

予算ページの更新ボタンを今月以外は見れないようにした
https://github.com/user-attachments/assets/21d622b0-0088-4f77-b2ac-f20b3e007dc1
Closes #96

💄 予算ページの更新ボタンを今月以外は見れないようにした (#96)

---

prisma/schema.prisma

prisma schemaのbinaryTargetsにdebian-openssl-3.0.xを追加し、デプロイした際の実行環境に合わせた。
それによって、認証後のエラーがなくなるようにした。
Closes #139 
認証後にPrismaの以下のエラーがなくなった。
`Prisma Client could not locate the Query Engine for runtime "debian-openssl-3.0.x".`

🐛 Prisma Clientの実行環境にdebian-openssl-3.0.xを追加した

---

next.config.mjs

ビルド後にserver.jsを実行できるように、 standaloneで実行する
公式を参考にして行なった。
https://github.com/vercel/next.js/blob/canary/examples/with-docker/Dockerfile
next.config.mjsを以下のようにすると、.next/standalone/server.js が作成された。
node sever.jsを実行するとうまく起動した。

✨standaloneをnext.configに追加した (#)

---

src/_components/features/sidebar/CreateExpenseDialog.tsx
src/_components/features/sidebar/ReceiptUpload.tsx
src/_components/features/sidebar/SidebarActions.ts
src/_components/features/sidebar/type.ts
src/lib/s3.ts

レシート解析をしなければ、レシートがアップロードされず、作成された出費を見てもレシートが登録されていない状況だった。
そのため、
- レシートをS3にアップロードするトリガーをアップロードボタンにし、解析ボタンではレシートアップロードを行わないようにした。
- 出費作成ダイアログで❌を押された際に、レシートをS3から削除するようにした。
- レシートの削除はバージョニングなしの完全削除としている。
- ([理由](https://github.com/ogaogs/receipt-scanner/issues/158#issuecomment-3289085388))
- レシート削除が失敗してもエラーは表示しないようにした。([理由](https://github.com/ogaogs/receipt-scanner/issues/158#issuecomment-3289121486))
1. レシート画像あり
1. 解析を押さずに作成し、作成された出費にレシート画像が含まれることを確認した。
2. 解析を実行し出費を作成し、作成された出費にレシート画像が含まれることを確認した。
3. レシート画像なし
1. レシートを登録せずに、出費を追加した際に、作成された出費にレシートなしの出費が作成されることを確認した。
3. ❌を押下すると、レシートが削除されることを確認した
closes #158

🐛 レシート解析を行わないとレシートがアップロードされないバグの解消 (#158)
